# FROM node:18-alpine AS base
# RUN apk add --no-cache libc6-compat
FROM node:20 AS base
RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY ./out/json/package.json .
COPY ./out/json/pnpm-lock.yaml .

COPY ./out/full/ .

RUN pnpm install --no-frozen-lockfile --prod=false

EXPOSE 3000

CMD ["pnpm", "run", "dev"]

# FROM node:20-slim

# RUN apt-get update && apt-get install -y procps \
#     && rm -rf /var/lib/apt/lists/*

# RUN npm install -g pnpm

# WORKDIR /app

# COPY . .

# # install all deps including devDependencies
# RUN pnpm install --frozen-lockfile --prod=false

# EXPOSE 3000
# CMD ["pnpm", "--filter", "api", "run", "dev"]