FROM node:20-slim

RUN apt-get update && apt-get install -y procps \
    && rm -rf /var/lib/apt/lists/*

RUN npm install -g pnpm

WORKDIR /app

COPY . .

# install all deps including devDependencies
RUN pnpm install --frozen-lockfile --prod=false

EXPOSE 3000
CMD ["pnpm", "--filter", "api", "run", "dev"]
